name: E2E cypress


on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-lastest

    strategy:
      matrix: 
        node-version: [22.x]
    steps: 
    - uses: actions/checkout@v3
    - name: E2E cypress
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run cypress run